//
//  StaticCityData.swift
//  TercihKilavuzu2022
//
//  Created by İsmail on 3.10.2021.
//

import Foundation

struct StaticCityData {
    var staticCityDataList: [City]
    
    init() {
        staticCityDataList = [
            City(id: 1, name: "ANKARA"),
            City(id: 2, name: "İSTANBUL"),
            City(id: 3, name: "İZMİR"),
            City(id: 4, name: "ADANA"),
            City(id: 5, name: "ADIYAMAN"),
            City(id: 6, name: "AFYONKARAHİSAR"),
            City(id: 7, name: "AĞRI"),
            City(id: 8, name: "AKSARAY"),
            City(id: 9, name: "AMASYA"),
            City(id: 10, name: "ANTALYA"),
            City(id: 11, name: "ARDAHAN"),
            City(id: 12, name: "ARTVİN"),
            City(id: 13, name: "AYDIN"),
            City(id: 14, name: "BALIKESİR"),
            City(id: 15, name: "BARTIN"),
            City(id: 16, name: "BATMAN"),
            City(id: 17, name: "BAYBURT"),
            City(id: 18, name: "BİLECİK"),
            City(id: 19, name: "BİNGÖL"),
            City(id: 20, name: "BİTLİS"),
            City(id: 21, name: "BOLU"),
            City(id: 22, name: "BURDUR"),
            City(id: 23, name: "BURSA"),
            City(id: 24, name: "ÇANAKKALE"),
            City(id: 25, name: "ÇANKIRI"),
            City(id: 26, name: "ÇORUM"),
            City(id: 27, name: "DENİZLİ"),
            City(id: 28, name: "DİYARBAKIR"),
            City(id: 29, name: "DÜZCE"),
            City(id: 30, name: "EDİRNE"),
            City(id: 31, name: "ELAZIĞ"),
            City(id: 32, name: "ERZİNCAN"),
            City(id: 33, name: "ESKİŞEHİR"),
            City(id: 34, name: "GAZİANTEP"),
            City(id: 35, name: "GİRESUN"),
            City(id: 36, name: "GÜMÜŞHANE"),
            City(id: 37, name: "HAKKARİ"),
            City(id: 38, name: "HATAY"),
            City(id: 39, name: "IĞDIR"),
            City(id: 40, name: "ISPARTA"),
            City(id: 41, name: "KAHRAMANMARAŞ"),
            City(id: 42, name: "KARABÜK"),
            City(id: 43, name: "KARAMAN"),
            City(id: 44, name: "KARS"),
            City(id: 45, name: "KASTAMONU"),
            City(id: 46, name: "KAYSERİ"),
            City(id: 47, name: "KİLİS"),
            City(id: 48, name: "KIRIKKALE"),
            City(id: 49, name: "KIRŞEHİR"),
            City(id: 50, name: "KOCAELİ"),
            City(id: 51, name: "KONYA"),
            City(id: 52, name: "KÜTAHYA"),
            City(id: 53, name: "MALATYA"),
            City(id: 54, name: "MANİSA"),
            City(id: 55, name: "MARDİN"),
            City(id: 56, name: "MERSİN"),
            City(id: 57, name: "MUĞLA"),
            City(id: 58, name: "MUŞ"),
            City(id: 59, name: "NEVŞEHİR"),
            City(id: 60, name: "NİĞDE"),
            City(id: 61, name: "ORDU"),
            City(id: 62, name: "OSMANİYE"),
            City(id: 63, name: "RİZE"),
            City(id: 64, name: "SAKARYA"),
            City(id: 65, name: "SAMSUN"),
            City(id: 66, name: "ŞANLIURFA"),
            City(id: 67, name: "SİİRT"),
            City(id: 68, name: "SİNOP"),
            City(id: 69, name: "SİVAS"),
            City(id: 70, name: "ŞIRNAK"),
            City(id: 71, name: "TEKİRDAĞ"),
            City(id: 72, name: "TOKAT"),
            City(id: 73, name: "TRABZON"),
            City(id: 74, name: "TUNCELİ"),
            City(id: 75, name: "UŞAK"),
            City(id: 76, name: "VAN"),
            City(id: 77, name: "YALOVA"),
            City(id: 78, name: "YOZGAT"),
            City(id: 79, name: "ZONGULDAK"),
            City(id: 80, name: "GAZİMAĞUSA-KKTC"),
            City(id: 81, name: "LEFKOŞA-KKTC"),
            City(id: 82, name: "BAKÜ-AZERBAYCAN"),
            City(id: 83, name: "GİRNE-KKTC"),
            City(id: 84, name: "TÜRKİSTAN-KAZAKİSTAN"),
            City(id: 85, name: "GÜZELYURT-KKTC"),
            City(id: 86, name: "BİŞKEK-KIRGIZİSTAN"),
            City(id: 87, name: "KOMRAT-MOLDOVA"),
            City(id: 88, name: "LEFKE-KKTC"),
            City(id: 89, name: "ÜSKÜP-MAKEDONYA")
        ]
    }
}
